SELECT
		 cf."In-Shop Date/Time",
		 cf."Out-Shop Date/Time",
		 lt."Truck VIN",
		 lt."Actual Del - Dealer",
		 lt."Est Del Dealer",
		 lt."Cost per Mile - (Maint)",
		 lt."Del Change Counter",
		 lt."Financial Cost",
		 lt."Fiscal Year",
		 lt."Id",
		 lt."In Service Date",
		 lt."Manufacturer",
		 lt."MPG",
		 lt."Non-Zonar",
		 lt."Original Del Dealer",
		 lt."Product Category",
		 lt."ptId",
		 lt."Re-Lease",
		 lt."Sales Start Date",
		 lt."testyr1",
		 lt."Truck Make",
		 lt."Truck Model",
		 lt."Truck Status",
		 lt."Truck Type",
		 lt."Truck Year",
		 lt."Unit Cost",
		 lt."Weekly Payment"
FROM  "qryCaseFiles" cf
RIGHT JOIN "qryLeasedTrucks" lt ON lt."Truck VIN"  = cf."Truck VIN"
	 AND	lt."Financial Cost"  > 0
	 AND	lt."Fiscal Year"  > 2020
	 AND	lt."Unit Cost"  > 115000  
GROUP BY cf."In-Shop Date/Time",
	 cf."Out-Shop Date/Time",
	 lt."Truck VIN",
	 lt."Actual Del - Dealer",
	 lt."Est Del Dealer",
	 lt."Cost per Mile - (Maint)",
	 lt."Del Change Counter",
	 lt."Financial Cost",
	 lt."Fiscal Year",
	 lt."Id",
	 lt."In Service Date",
	 lt."Manufacturer",
	 lt."MPG",
	 lt."Non-Zonar",
	 lt."Original Del Dealer",
	 lt."Product Category",
	 lt."ptId",
	 lt."Re-Lease",
	 lt."Sales Start Date",
	 lt."testyr1",
	 lt."Truck Make",
	 lt."Truck Model",
	 lt."Truck Status",
	 lt."Truck Type",
	 lt."Truck Year",
	 lt."Unit Cost",
	  lt."Weekly Payment" 
